### ISSUE TITLE
Talismane-fr.1.2.9b  - java.lang.NullPointerException

### ISSUE THREAD

**Issue by fauconnier** [joliciel-informatique/talismane#1]
Avec la version talismane-fr.1.2.9b.jar,
la phrase :
"
Sont autorisés par la DASS dans les piscines publiques en France : le chlore liquide et le brome liquide (la version liquide du brome étant difficile à trouver en France, la croyance veut que seul le chlore liquide soit autorisé).
"
provoque une erreur :
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.simontuffs.onejar.Boot.run(Boot.java:315)
    at com.simontuffs.onejar.Boot.main(Boot.java:152)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at com.joliciel.talismane.AbstractTalismane.analyse(AbstractTalismane.java:502)
    at com.joliciel.talismane.AbstractTalismane.runCommand(AbstractTalismane.java:112)
    at com.joliciel.talismane.fr.TalismaneFrench.main(TalismaneFrench.java:47)
    ... 6 more
Caused by: java.lang.NullPointerException
    at com.joliciel.talismane.parser.TransitionBasedParser.parseSentence(TransitionBasedParser.java:225)
    at com.joliciel.talismane.AbstractTalismane.analyse(AbstractTalismane.java:490)
    ... 8 more

Avec la version talismane-fr-1.0.3b.jar, l'erreur n'apparaît pas.
Un problème de parsing?

**Comment by flutura37** [comment]
J'ai eu ce message en essayant de démarrer l'analyse au POS sur un fichier dans lequel j'ai procédé à la modification d'une étiquette. 

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.simontuffs.onejar.Boot.run(Boot.java:315)
	at com.simontuffs.onejar.Boot.main(Boot.java:152)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.joliciel.talismane.TalismaneImpl.process(TalismaneImpl.java:405)
	at com.joliciel.talismane.fr.TalismaneFrench.main(TalismaneFrench.java:225)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.joliciel.talismane.TalismaneImpl.analyse(TalismaneImpl.java:760)
	at com.joliciel.talismane.TalismaneImpl.process(TalismaneImpl.java:150)
	... 7 more
Que peut être le problème?

**Comment by urieli** [comment]
Il faut me donner la version exacte de Talismane utilisée, afin que je
puisse avoir une idée du problème.

Dans le cas d'une version antérieure à 2.4.1b, il serait utile d'essayer
d'abord de réproduire l'erreur avec cette dernière version, sauf s'il y a
une raison particulière pour utiliser une version antérieure.

Si vous arriver à réproduire l'erreur avec la version 2.4.1b, merci de
m'envoyer la commande exacte executée, avec tous les fichiers auquels la
commande fait référence.

**Comment by flutura37** [comment]
J'ai pas eu un besoin particulier de l'ancienne version. J'ai utilisé la nouvelle, et le problème n'apparait plus! 
Merci.
